package dev.bukkitkit.processor.generate;

import dev.bukkitkit.api.BukkitKitSymbols;
import dev.bukkitkit.processor.builtins.BuiltInTypes;
import dev.bukkitkit.processor.model.ComponentModel;
import dev.bukkitkit.processor.model.ComponentModel.InjectionKind;
import dev.bukkitkit.processor.model.ComponentModel.WiredField;
import dev.bukkitkit.processor.model.EventMethod;
import dev.bukkitkit.processor.model.LifecycleMethod;
import dev.bukkitkit.processor.model.ScheduledMethod;

import com.squareup.javapoet.ClassName;
import com.squareup.javapoet.CodeBlock;
import com.squareup.javapoet.FieldSpec;
import com.squareup.javapoet.JavaFile;
import com.squareup.javapoet.MethodSpec;
import com.squareup.javapoet.TypeSpec;

import javax.annotation.processing.Filer;
import javax.lang.model.element.Modifier;
import javax.tools.FileObject;
import javax.tools.StandardLocation;
import java.io.IOException;
import java.io.Writer;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Generates {@code BukkitKitInit} (holds component instances) and the bootstrap resource index.
 */
public final class BootstrapGenerator {

    private static final ClassName KIT_BOOTSTRAP =
            ClassName.get("dev.bukkitkit.paper", "KitBootstrap");
    private static final ClassName PLATFORM_SERVICES =
            ClassName.get("dev.bukkitkit.paper", "PlatformServices");
    private static final ClassName BUKKIT_KIT_EXCEPTION =
            ClassName.get("dev.bukkitkit.api", "BukkitKitException");
    private static final ClassName FIELD_WIRE =
            ClassName.get("dev.bukkitkit.core", "FieldWire");
    private static final ClassName BUKKIT_EVENT_PRIORITY =
            ClassName.get("org.bukkit.event", "EventPriority");
    private static final ClassName HANDLER_LIST =
            ClassName.get("org.bukkit.event", "HandlerList");
    private static final ClassName BUKKIT_LISTENER =
            ClassName.get("org.bukkit.event", "Listener");

    private final Filer filer;

    public BootstrapGenerator(Filer filer) {
        this.filer = filer;
    }

    public void write(List<ComponentModel> orderedComponents) throws IOException {
        String packageName = commonPackage(orderedComponents);
        String simpleName = "BukkitKitInit";
        String fqcn = packageName.isEmpty() ? simpleName : packageName + "." + simpleName;

        Map<String, String> instanceFields = allocateInstanceFields(orderedComponents);

        TypeSpec.Builder type = TypeSpec.classBuilder(simpleName)
                .addModifiers(Modifier.PUBLIC, Modifier.FINAL)
                .addSuperinterface(KIT_BOOTSTRAP)
                .addJavadoc("Generated by BukkitKit — do not edit.")
                .addMethod(MethodSpec.constructorBuilder().addModifiers(Modifier.PUBLIC).build());

        for (ComponentModel component : orderedComponents) {
            ClassName typeName = ClassName.bestGuess(component.typeName());
            String field = instanceFields.get(component.typeName());
            type.addField(FieldSpec.builder(typeName, field, Modifier.PRIVATE).build());
            if (component.hasEvents() && !component.alreadyListener()) {
                type.addField(FieldSpec.builder(BUKKIT_LISTENER, listenerField(field), Modifier.PRIVATE, Modifier.FINAL)
                        .initializer("new $T() {}", BUKKIT_LISTENER)
                        .build());
            }
        }

        type.addMethod(buildStart(orderedComponents, instanceFields));
        type.addMethod(buildStop(orderedComponents, instanceFields));

        JavaFile.builder(packageName, type.build())
                .skipJavaLangImports(true)
                .build()
                .writeTo(filer);

        FileObject resource = filer.createResource(
                StandardLocation.CLASS_OUTPUT,
                "",
                BukkitKitSymbols.BOOTSTRAP_RESOURCE);
        try (Writer writer = resource.openWriter()) {
            writer.write(fqcn);
            writer.write('\n');
        }
    }

    private MethodSpec buildStart(
            List<ComponentModel> ordered,
            Map<String, String> instanceFields) {
        MethodSpec.Builder method = MethodSpec.methodBuilder("start")
                .addAnnotation(Override.class)
                .addModifiers(Modifier.PUBLIC)
                .addParameter(PLATFORM_SERVICES, "s");

        for (ComponentModel component : ordered) {
            ClassName type = ClassName.bestGuess(component.typeName());
            String field = instanceFields.get(component.typeName());
            if (component.kind() == InjectionKind.FIELD) {
                method.addStatement("this.$L = new $T()", field, type);
                for (WiredField wired : component.wiredFields()) {
                    method.addStatement(
                            "$T.set(this.$L, $S, $L)",
                            FIELD_WIRE,
                            field,
                            wired.fieldName(),
                            dependencyExpr(wired.typeName(), instanceFields));
                }
            } else {
                method.addStatement(
                        "this.$L = new $T($L)",
                        field,
                        type,
                        constructorArgs(component, instanceFields));
            }
        }

        for (ComponentModel component : ordered) {
            if (!component.hasOnEnable()) {
                continue;
            }
            String field = instanceFields.get(component.typeName());
            method.beginControlFlow("try");
            for (LifecycleMethod enable : component.onEnableMethods()) {
                method.addStatement("this.$L.$L()", field, enable.methodName());
            }
            method.nextControlFlow("catch ($T ex)", RuntimeException.class);
            method.addStatement(
                    "throw new $T($S, ex)",
                    BUKKIT_KIT_EXCEPTION,
                    "BukkitKit: onEnable failed for " + component.typeName());
            method.endControlFlow();
        }

        for (ComponentModel component : ordered) {
            String field = instanceFields.get(component.typeName());
            for (ScheduledMethod scheduled : component.scheduledMethods()) {
                emitSchedule(method, field, scheduled);
            }
        }

        for (ComponentModel component : ordered) {
            String field = instanceFields.get(component.typeName());
            CodeBlock listenerExpr = listenerExpr(component, field);
            for (EventMethod event : component.eventMethods()) {
                emitEvent(method, field, listenerExpr, event);
            }
        }

        return method.build();
    }

    private void emitEvent(
            MethodSpec.Builder method,
            String instanceField,
            CodeBlock listenerExpr,
            EventMethod event) {
        ClassName eventType = ClassName.bestGuess(event.eventTypeName());
        method.addStatement(
                "s.pluginManager().registerEvent($T.class, $L, $T.$L,"
                        + " (listener, e) -> this.$L.$L(($T) e), s.javaPlugin(), $L)",
                eventType,
                listenerExpr,
                BUKKIT_EVENT_PRIORITY,
                event.priority().name(),
                instanceField,
                event.methodName(),
                eventType,
                event.ignoreCancelled());
    }

    private void emitSchedule(MethodSpec.Builder method, String field, ScheduledMethod scheduled) {
        long delayTicks = scheduled.delayTicks();
        boolean async = scheduled.async();
        String methodName = scheduled.methodName();

        if (scheduled.repeating()) {
            long periodTicks = scheduled.periodTicks();
            if (scheduled.booleanReturn()) {
                method.addStatement(
                        "s.kitScheduler().runRepeating($LL, $LL, $L, () -> this.$L.$L())",
                        delayTicks,
                        periodTicks,
                        async,
                        field,
                        methodName);
            } else {
                method.addStatement(
                        "s.kitScheduler().runRepeating($LL, $LL, $L, () -> { this.$L.$L(); return true; })",
                        delayTicks,
                        periodTicks,
                        async,
                        field,
                        methodName);
            }
        } else if (scheduled.booleanReturn()) {
            method.addStatement(
                    "s.kitScheduler().runLater($LL, $L, () -> { this.$L.$L(); })",
                    delayTicks,
                    async,
                    field,
                    methodName);
        } else {
            method.addStatement(
                    "s.kitScheduler().runLater($LL, $L, () -> this.$L.$L())",
                    delayTicks,
                    async,
                    field,
                    methodName);
        }
    }

    private CodeBlock constructorArgs(ComponentModel component, Map<String, String> instanceFields) {
        CodeBlock.Builder args = CodeBlock.builder();
        for (int i = 0; i < component.dependencies().size(); i++) {
            if (i > 0) {
                args.add(", ");
            }
            args.add(dependencyExpr(component.dependencies().get(i), instanceFields));
        }
        return args.build();
    }

    private CodeBlock dependencyExpr(String dep, Map<String, String> instanceFields) {
        if (BuiltInTypes.isBuiltIn(dep)) {
            return CodeBlock.of("s.$L()", BuiltInTypes.accessor(dep));
        }
        String field = instanceFields.get(dep);
        if (field == null) {
            throw new IllegalStateException("BukkitKit: missing instance field for " + dep);
        }
        return CodeBlock.of("this.$L", field);
    }

    private CodeBlock listenerExpr(ComponentModel component, String instanceField) {
        if (component.alreadyListener()) {
            return CodeBlock.of("this.$L", instanceField);
        }
        return CodeBlock.of("this.$L", listenerField(instanceField));
    }

    private MethodSpec buildStop(
            List<ComponentModel> ordered,
            Map<String, String> instanceFields) {
        MethodSpec.Builder method = MethodSpec.methodBuilder("stop")
                .addAnnotation(Override.class)
                .addModifiers(Modifier.PUBLIC);

        for (int i = ordered.size() - 1; i >= 0; i--) {
            ComponentModel component = ordered.get(i);
            if (!component.hasEvents()) {
                continue;
            }
            String field = instanceFields.get(component.typeName());
            CodeBlock listener = listenerExpr(component, field);
            method.beginControlFlow("if ($L != null)", listener);
            method.addStatement("$T.unregisterAll($L)", HANDLER_LIST, listener);
            method.endControlFlow();
        }

        for (int i = ordered.size() - 1; i >= 0; i--) {
            ComponentModel component = ordered.get(i);
            if (!component.hasOnDisable()) {
                continue;
            }
            String field = instanceFields.get(component.typeName());
            List<LifecycleMethod> disables = component.onDisableMethods();
            method.beginControlFlow("try");
            method.beginControlFlow("if (this.$L != null)", field);
            for (int j = disables.size() - 1; j >= 0; j--) {
                method.addStatement("this.$L.$L()", field, disables.get(j).methodName());
            }
            method.endControlFlow();
            method.nextControlFlow("catch ($T ignored)", RuntimeException.class);
            method.endControlFlow();
        }

        for (int i = ordered.size() - 1; i >= 0; i--) {
            ComponentModel component = ordered.get(i);
            String field = instanceFields.get(component.typeName());
            method.addStatement("this.$L = null", field);
        }
        return method.build();
    }

    private static String listenerField(String instanceField) {
        return instanceField + "Listener";
    }

    private static Map<String, String> allocateInstanceFields(List<ComponentModel> components) {
        Map<String, String> fields = new HashMap<>();
        Set<String> used = new HashSet<>();
        for (ComponentModel component : components) {
            String base = decapitalize(component.simpleName());
            String name = base;
            int n = 2;
            while (!used.add(name)) {
                name = base + n++;
            }
            fields.put(component.typeName(), name);
        }
        return fields;
    }

    private static String decapitalize(String name) {
        if (name.isEmpty()) {
            return name;
        }
        if (name.length() > 1 && Character.isUpperCase(name.charAt(0)) && Character.isUpperCase(name.charAt(1))) {
            return name;
        }
        return Character.toLowerCase(name.charAt(0)) + name.substring(1);
    }

    private static String commonPackage(List<ComponentModel> components) {
        List<String> packages = components.stream()
                .map(ComponentModel::packageName)
                .distinct()
                .sorted()
                .toList();
        if (packages.isEmpty()) {
            return "dev.bukkitkit.generated";
        }
        String common = packages.getFirst();
        for (String pkg : packages) {
            common = longestCommonPackagePrefix(common, pkg);
        }
        return common.isEmpty() ? "dev.bukkitkit.generated" : common;
    }

    private static String longestCommonPackagePrefix(String a, String b) {
        String[] left = a.split("\\.", -1);
        String[] right = b.split("\\.", -1);
        int n = Math.min(left.length, right.length);
        int i = 0;
        while (i < n && left[i].equals(right[i])) {
            i++;
        }
        if (i == 0) {
            return "";
        }
        StringBuilder sb = new StringBuilder(left[0]);
        for (int j = 1; j < i; j++) {
            sb.append('.').append(left[j]);
        }
        return sb.toString();
    }
}
