package dev.bukkitkit.processor.generate;

import dev.bukkitkit.api.BukkitKitSymbols;
import dev.bukkitkit.processor.builtins.BuiltInTypes;
import dev.bukkitkit.processor.model.ComponentModel;
import dev.bukkitkit.processor.model.ComponentModel.InjectionKind;
import dev.bukkitkit.processor.model.ComponentModel.WiredField;
import dev.bukkitkit.processor.model.ScheduledMethod;

import com.squareup.javapoet.ClassName;
import com.squareup.javapoet.CodeBlock;
import com.squareup.javapoet.JavaFile;
import com.squareup.javapoet.MethodSpec;
import com.squareup.javapoet.TypeSpec;

import javax.annotation.processing.Filer;
import javax.lang.model.element.Modifier;
import javax.tools.FileObject;
import javax.tools.StandardLocation;
import java.io.IOException;
import java.io.Writer;
import java.util.List;
import java.util.Set;

/**
 * Generates {@code BukkitKitInit} and the bootstrap resource index.
 */
public final class BootstrapGenerator {

    private static final ClassName KIT_BOOTSTRAP =
            ClassName.get("dev.bukkitkit.paper", "KitBootstrap");
    private static final ClassName PLATFORM_SERVICES =
            ClassName.get("dev.bukkitkit.paper", "PlatformServices");
    private static final ClassName LIFECYCLES =
            ClassName.get("dev.bukkitkit.api", "Lifecycles");
    private static final ClassName BUKKIT_KIT_EXCEPTION =
            ClassName.get("dev.bukkitkit.api", "BukkitKitException");

    private final Filer filer;
    private Set<String> pluginTypeNames = Set.of();

    public BootstrapGenerator(Filer filer) {
        this.filer = filer;
    }

    public void write(List<ComponentModel> orderedComponents, Set<String> pluginTypeNames) throws IOException {
        this.pluginTypeNames = pluginTypeNames == null ? Set.of() : Set.copyOf(pluginTypeNames);
        String packageName = commonPackage(orderedComponents);
        String simpleName = "BukkitKitInit";
        String fqcn = packageName.isEmpty() ? simpleName : packageName + "." + simpleName;

        TypeSpec typeSpec = TypeSpec.classBuilder(simpleName)
                .addModifiers(Modifier.PUBLIC, Modifier.FINAL)
                .addSuperinterface(KIT_BOOTSTRAP)
                .addJavadoc("Generated by BukkitKit — do not edit.")
                .addMethod(MethodSpec.constructorBuilder().addModifiers(Modifier.PUBLIC).build())
                .addMethod(buildStart(orderedComponents))
                .addMethod(buildStop(orderedComponents))
                .build();

        JavaFile.builder(packageName, typeSpec)
                .skipJavaLangImports(true)
                .build()
                .writeTo(filer);

        FileObject resource = filer.createResource(
                StandardLocation.CLASS_OUTPUT,
                "",
                BukkitKitSymbols.BOOTSTRAP_RESOURCE);
        try (Writer writer = resource.openWriter()) {
            writer.write(fqcn);
            writer.write('\n');
        }
    }

    private MethodSpec buildStart(List<ComponentModel> ordered) {
        MethodSpec.Builder method = MethodSpec.methodBuilder("start")
                .addAnnotation(Override.class)
                .addModifiers(Modifier.PUBLIC)
                .addParameter(PLATFORM_SERVICES, "s");

        int local = 0;
        for (ComponentModel component : ordered) {
            ClassName type = ClassName.bestGuess(component.typeName());
            if (component.kind() == InjectionKind.FIELD) {
                String varName = "c" + local++;
                method.addStatement("$T $L = new $T()", type, varName, type);
                method.addStatement("$L.$L($L)", varName, BukkitKitSymbols.WIRE_METHOD, wireArgs(component));
                method.addStatement("$T.$L($L)", type, BukkitKitSymbols.BIND_METHOD, varName);
            } else {
                method.addStatement(
                        "$T.$L(new $T($L))",
                        type,
                        BukkitKitSymbols.BIND_METHOD,
                        type,
                        constructorArgs(component));
            }
        }

        for (ComponentModel component : ordered) {
            ClassName type = ClassName.bestGuess(component.typeName());
            method.beginControlFlow("try");
            method.addStatement(
                    "$T.enable($T.$L)",
                    LIFECYCLES,
                    type,
                    BukkitKitSymbols.INSTANCE_FIELD);
            method.nextControlFlow("catch ($T ex)", RuntimeException.class);
            method.addStatement(
                    "throw new $T($S, ex)",
                    BUKKIT_KIT_EXCEPTION,
                    "BukkitKit: onEnable failed for " + component.typeName());
            method.endControlFlow();
        }

        for (ComponentModel component : ordered) {
            ClassName type = ClassName.bestGuess(component.typeName());
            for (ScheduledMethod scheduled : component.scheduledMethods()) {
                emitSchedule(method, type, scheduled);
            }
        }

        return method.build();
    }

    private void emitSchedule(MethodSpec.Builder method, ClassName type, ScheduledMethod scheduled) {
        long delayTicks = scheduled.delayTicks();
        boolean async = scheduled.async();
        String methodName = scheduled.methodName();

        if (scheduled.repeating()) {
            long periodTicks = scheduled.periodTicks();
            if (scheduled.booleanReturn()) {
                method.addStatement(
                        "s.kitScheduler().runRepeating($LL, $LL, $L, () -> $T.$L.$L())",
                        delayTicks,
                        periodTicks,
                        async,
                        type,
                        BukkitKitSymbols.INSTANCE_FIELD,
                        methodName);
            } else {
                method.addStatement(
                        "s.kitScheduler().runRepeating($LL, $LL, $L, () -> { $T.$L.$L(); return true; })",
                        delayTicks,
                        periodTicks,
                        async,
                        type,
                        BukkitKitSymbols.INSTANCE_FIELD,
                        methodName);
            }
        } else if (scheduled.booleanReturn()) {
            method.addStatement(
                    "s.kitScheduler().runLater($LL, $L, () -> { $T.$L.$L(); })",
                    delayTicks,
                    async,
                    type,
                    BukkitKitSymbols.INSTANCE_FIELD,
                    methodName);
        } else {
            method.addStatement(
                    "s.kitScheduler().runLater($LL, $L, () -> $T.$L.$L())",
                    delayTicks,
                    async,
                    type,
                    BukkitKitSymbols.INSTANCE_FIELD,
                    methodName);
        }
    }

    private CodeBlock constructorArgs(ComponentModel component) {
        CodeBlock.Builder args = CodeBlock.builder();
        for (int i = 0; i < component.dependencies().size(); i++) {
            if (i > 0) {
                args.add(", ");
            }
            args.add(dependencyExpr(component.dependencies().get(i)));
        }
        return args.build();
    }

    private CodeBlock wireArgs(ComponentModel component) {
        CodeBlock.Builder args = CodeBlock.builder();
        List<WiredField> fields = component.wiredFields();
        for (int i = 0; i < fields.size(); i++) {
            if (i > 0) {
                args.add(", ");
            }
            args.add(dependencyExpr(fields.get(i).typeName()));
        }
        return args.build();
    }

    private CodeBlock dependencyExpr(String dep) {
        if (BuiltInTypes.isBuiltIn(dep)) {
            return CodeBlock.of("s.$L()", BuiltInTypes.accessor(dep));
        }
        if (pluginTypeNames.contains(dep)) {
            return CodeBlock.of("s.plugin($T.class)", ClassName.bestGuess(dep));
        }
        return CodeBlock.of("$T.$L", ClassName.bestGuess(dep), BukkitKitSymbols.INSTANCE_FIELD);
    }

    private MethodSpec buildStop(List<ComponentModel> ordered) {
        MethodSpec.Builder method = MethodSpec.methodBuilder("stop")
                .addAnnotation(Override.class)
                .addModifiers(Modifier.PUBLIC);

        for (int i = ordered.size() - 1; i >= 0; i--) {
            ComponentModel component = ordered.get(i);
            ClassName type = ClassName.bestGuess(component.typeName());
            method.beginControlFlow("try");
            method.addStatement(
                    "$T.disable($T.$L)",
                    LIFECYCLES,
                    type,
                    BukkitKitSymbols.INSTANCE_FIELD);
            method.nextControlFlow("catch ($T ignored)", RuntimeException.class);
            method.endControlFlow();
        }

        for (int i = ordered.size() - 1; i >= 0; i--) {
            ComponentModel component = ordered.get(i);
            ClassName type = ClassName.bestGuess(component.typeName());
            method.addStatement("$T.$L()", type, BukkitKitSymbols.UNBIND_METHOD);
        }
        return method.build();
    }

    private static String commonPackage(List<ComponentModel> components) {
        List<String> packages = components.stream()
                .map(ComponentModel::packageName)
                .distinct()
                .sorted()
                .toList();
        if (packages.isEmpty()) {
            return "dev.bukkitkit.generated";
        }
        String common = packages.getFirst();
        for (String pkg : packages) {
            common = longestCommonPackagePrefix(common, pkg);
        }
        return common.isEmpty() ? "dev.bukkitkit.generated" : common;
    }

    private static String longestCommonPackagePrefix(String a, String b) {
        String[] left = a.split("\\.", -1);
        String[] right = b.split("\\.", -1);
        int n = Math.min(left.length, right.length);
        int i = 0;
        while (i < n && left[i].equals(right[i])) {
            i++;
        }
        if (i == 0) {
            return "";
        }
        StringBuilder sb = new StringBuilder(left[0]);
        for (int j = 1; j < i; j++) {
            sb.append('.').append(left[j]);
        }
        return sb.toString();
    }
}
