package dev.bukkitkit.processor.generate;

import dev.bukkitkit.processor.model.PluginModel;

import com.squareup.javapoet.ClassName;
import com.squareup.javapoet.JavaFile;
import com.squareup.javapoet.MethodSpec;
import com.squareup.javapoet.TypeSpec;

import javax.annotation.processing.Filer;
import javax.lang.model.element.Modifier;
import java.io.IOException;

/**
 * Generates the {@code JavaPlugin} entry class for a {@code @BukkitKit} marker.
 */
public final class PluginGenerator {

    private static final ClassName JAVA_PLUGIN =
            ClassName.get("org.bukkit.plugin.java", "JavaPlugin");
    private static final ClassName SUPPORT =
            ClassName.get("dev.bukkitkit.paper", "BukkitKitSupport");

    private final Filer filer;

    public PluginGenerator(Filer filer) {
        this.filer = filer;
    }

    public void write(PluginModel plugin) throws IOException {
        MethodSpec onEnable = MethodSpec.methodBuilder("onEnable")
                .addAnnotation(Override.class)
                .addModifiers(Modifier.PUBLIC)
                .addStatement("$T.enable(this)", SUPPORT)
                .build();

        MethodSpec onDisable = MethodSpec.methodBuilder("onDisable")
                .addAnnotation(Override.class)
                .addModifiers(Modifier.PUBLIC)
                .addStatement("$T.disable(this)", SUPPORT)
                .build();

        TypeSpec typeSpec = TypeSpec.classBuilder(plugin.generatedSimpleName())
                .addModifiers(Modifier.PUBLIC, Modifier.FINAL)
                .superclass(JAVA_PLUGIN)
                .addJavadoc(
                        "Generated by BukkitKit for {@code $L} — do not edit.\n",
                        plugin.typeName())
                .addMethod(MethodSpec.constructorBuilder().addModifiers(Modifier.PUBLIC).build())
                .addMethod(onEnable)
                .addMethod(onDisable)
                .build();

        JavaFile.builder(plugin.packageName(), typeSpec)
                .skipJavaLangImports(true)
                .build()
                .writeTo(filer);
    }
}
